name: Build Container Images

on:
  push:
    tags:
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  IMAGES: docker.io/msevcik/hapi
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare settings.xml
        run: |
          cp settings.xml.template settings.xml
          sed -i 's/{REPLACE_TOKEN}/'${{ secrets.GITHUB_TOKEN }}'/g' settings.xml

      - name: Container meta for default (distroless) image
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGES }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push default (distroless) image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}
          target: default